# Generated by Django 4.0.6 on 2022-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FULLNAME', models.CharField(max_length=50)),
                ('EMAIL_ADDRESS', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=50)),
            ],
        ),
    ]
