# Generated by Django 4.0.6 on 2022-07-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourName', models.CharField(max_length=350)),
                ('Email', models.EmailField(max_length=254)),
                ('AdditionalDetails', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='OurNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterYourEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
