# Generated by Django 4.0.6 on 2022-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_givefeedback_ournewsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='IMAGE',
            field=models.ImageField(default='anything', upload_to='profile'),
        ),
    ]
