# Generated by Django 4.0.6 on 2022-07-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_userregister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='IMAGE',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
