# Generated by Django 4.0.6 on 2022-07-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_userregister_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoryname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dnotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('File', models.FileField(upload_to='notes')),
                ('connect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.category')),
            ],
        ),
    ]
