# Generated by Django 4.0.4 on 2022-07-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_category_dnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnotes',
            old_name='connect',
            new_name='category',
        ),
    ]
